FROM gradle:jdk21 AS builder
WORKDIR /builder
COPY build.gradle settings.gradle ./
RUN gradle dependencies
COPY src ./src
RUN gradle build


FROM bellsoft/liberica-openjre-alpine:21
RUN apk upgrade --no-cache
EXPOSE 8080
WORKDIR /app
COPY --from=builder /builder/build/libs/*.jar ./*.jar
ENTRYPOINT ["java","-jar","./*.jar"]