FROM gradle:jdk21 AS builder
WORKDIR /builder
COPY build.gradle settings.gradle ./
COPY src ./src
RUN gradle build

FROM eclipse-temurin:21-jre-alpine
EXPOSE 8080
WORKDIR /app
COPY --from=builder /builder/build/libs/*.jar ./*.jar
ENTRYPOINT ["java","-jar","./*.jar"]