spring:
  application:
    name: plutus
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
  datasource:
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000/realms/xStock"
          audiences:
            - account
  threads:
    virtual:
      enabled: true

springdoc:
  show-actuator: true
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: health, openapi, swagger-ui
  server:
    port: 9090