spring:
  application:
    name: plutus
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
        hbm2ddl:
          create_namespaces: true
  datasource:
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://auth.xstock.vn/realms/xStock"
          audiences:
            - account
  aot:
    enabled: false
  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs