spring:
  application:
    name: plutus
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000/realms/xStock"
          audiences:
            - account
            - plutus