spring:
  application:
    name: plutus
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/xstock
    username: data_admin
    password: data
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000/realms/xStock"
          audiences:
            - account
            - plutus
  output:
    ansi:
      enabled: always