logging:
  level:
    org.springframework.security: TRACE

spring:
  application:
    name: plutus
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/xstock
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
          audiences: xstock-client
  output:
    ansi:
      enabled: always